routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CharacterController;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\RombelController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\UserController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth')->name('welcome');
Route::get('/profile', [UserController::class, 'profile'])->name('profile');
Route::post('/avatar-post', [UserController::class, 'update_profile'])->name('profile.post');
Route::post('/change-password-post', [UserController::class, 'change_password'])->name('password.post');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('karakter', CharacterController::class);
Route::resource('siswa', StudentController::class);
Route::resource('rombel', RombelController::class);
Route::resource('jurusan', JurusanController::class);

app/Models/Character.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Character extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function student()
    {
        return $this->belongsTo(Student::class, 'siswa_id', 'id');
    }
}

app/Http/Controllers/CharacterController.php
<?php

namespace App\Http\Controllers;

use App\Models\CategoryCharacter;
use App\Models\Character;
use App\Models\Student;
use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;

class CharacterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Paginator::useBootstrap();
        $search = request()->query('search');

        if($search)
        {
            $characters = Character::with('student')->where('siswa_id', 'LIKE', "%{$search}%")->paginate(10);
        }else {
            $characters = Character::with('student')->latest()->paginate(10);
        }

        return view('characters.index', [
            'characters' => $characters
        ])
        ->with('i');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $students = Student::all();
        return view('characters.create', compact('students'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'karakter' => 'required',
            'siswa_id' => 'required',
            'capaian' => 'required|numeric',
            'deskripsi' => 'required',
        ]);

        Character::create($request->all());

        return redirect()->route('karakter.index')->with('success', 'Karakter berhasil dibuat!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $students = Student::all();
        $character = Character::findOrFail($id);

        return view('characters.edit', compact('character', 'students'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'karakter' => 'required',
            'siswa_id' => 'required',
            'capaian' => 'required|numeric',
            'deskripsi' => 'required',
        ]);

        $character = Character::findOrFail($id);
        $character->update($request->all());

        return redirect()->route('karakter.index')->with('success', 'Karakter berhasil diupdate!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $character = Character::findOrFail($id);
        $character->delete();

        return redirect()->route('karakter.index')->with('success', 'Karakter berhasil dihapus!');
    }
}

resources/views/characters/create.blade.php
@extends('layouts.admin.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Form Validation</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="index-2.html">Home</a>
                  </li>
                  <li class="breadcrumb-item"><a href="#">Forms</a>
                  </li>
                  <li class="breadcrumb-item active">Form Validation
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
            <div class="dropdown">
              <a class="btn-icon btn btn-danger btn-round btn-sm dropdown-toggle" href="{{ route('karakter.index') }}">Back</a>
            </div>
          </div>
        </div>
      </div>
      <div class="content-body"><!-- Validation -->
<section class="bs-validation">
<div class="row">
  <!-- Bootstrap Validation -->
  <div class="col-md-12 col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Bootstrap Validation</h4>
      </div>
      <div class="card-body">
        <form class="needs-validation" method="POST" action="{{ route('karakter.store') }}">
            @csrf
          <div class="form-group">
            <label class="form-label" for="basic-addon-name">Nomor Induk (NIS/NISN)</label>
            <select class="form-control" name="siswa_id" id="select-country1" required>
                <option value="" disabled selected>Pilih Nomor Induk</option>
                @foreach ($students as $student)
                <option value="{{ $student->id }}">{{ $student->nomor_induk }}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
            <label class="form-label" for="basic-default-email1">Category Karakter</label>
            <select class="form-control" name="karakter" id="select-country1" required>
                <option value="" disabled selected>Pilih Category Karakter</option>
                <option value="Religius">Religius</option>
                <option value="Disiplin">Disiplin</option>
                <option value="Tanggung Jawab">Tanggung Jawab</option>
                <option value="Mandiri">Mandiri</option>
                <option value="Literasi">Literasi</option>
              </select>
          </div>
          <div class="form-group">
            <label for="select-country1">Capaian</label>
            <input
              type="text"
              id="basic-default-password1"
              class="form-control"
              name="capaian"
              placeholder="Capaian"
              required
            />
          </div>
          <div class="form-group">
            <label for="dob-bootstrap-val">Deskripsi</label>
            <textarea type="text"
            id="dob-bootstrap-val"
            class="form-control"
            name="deskripsi"
            placeholder="Deskripsi"
            required cols="30" rows="10"></textarea>
          </div>
          <div class="alert alert-danger mt-1 alert-validation-msg" role="alert">
            <div class="alert-body">
              <i data-feather="info" class="mr-50 align-middle"></i>
              <span><strong>Note:</strong> Harap mengisi format sesuai contoh yang ada di dalam kurung!</span>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- /Bootstrap Validation -->
</div>
</section>
<!-- /Validation -->

      </div>
    </div>
  </div>
@endsection

resources/views/characters/edit.blade.php
@extends('layouts.admin.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Form Validation</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="index-2.html">Home</a>
                  </li>
                  <li class="breadcrumb-item"><a href="#">Forms</a>
                  </li>
                  <li class="breadcrumb-item active">Form Validation
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
            <div class="dropdown">
              <a class="btn-icon btn btn-danger btn-round btn-sm dropdown-toggle" href="{{ route('karakter.index') }}">Back</a>
            </div>
          </div>
        </div>
      </div>
      <div class="content-body"><!-- Validation -->
<section class="bs-validation">
<div class="row">
  <!-- Bootstrap Validation -->
  <div class="col-md-12 col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Bootstrap Validation</h4>
      </div>
      <div class="card-body">
        <form class="needs-validation" method="POST" action="{{ route('karakter.update', $character->id) }}">
            @csrf
            @method('PUT')
          <div class="form-group">
            <label class="form-label" for="basic-addon-name">Nomor Induk (NIS/NISN)</label>
            <select class="form-control" name="nomor_induk" id="select-country1" required>
                <option value="" disabled selected>Pilih Nomor Induk</option>
                <option value="{{ $character->student->id }}">{{ $character->student->nomor_induk }}</option>
              </select>
          </div>
          <div class="form-group">
            <label class="form-label" for="basic-default-email1">Category Karakter</label>
            <select class="form-control" name="karakter" id="select-country1" required>
                <option value="" disabled selected>Pilih Category Karakter</option>
                <option value="Religius">Religius</option>
                <option value="Disiplin">Disiplin</option>
                <option value="Tanggung Jawab">Tanggung Jawab</option>
                <option value="Mandiri">Mandiri</option>
                <option value="Literasi">Literasi</option>
              </select>
          </div>
          <div class="form-group">
            <label for="select-country1">Capaian</label>
            <input
              type="text"
              id="basic-default-password1"
              class="form-control"
              name="capaian"
              value="{{ $character->capaian }}"
              placeholder="Capaian"
              required
            />
          </div>
          <div class="form-group">
            <label for="dob-bootstrap-val">Deskripsi</label>
            <textarea type="text"
            id="dob-bootstrap-val"
            class="form-control"
            name="deskripsi"
            placeholder="Deskripsi"
            required cols="30" rows="10">{{ $character->deskripsi }}</textarea>
          </div>
          <div class="alert alert-danger mt-1 alert-validation-msg" role="alert">
            <div class="alert-body">
              <i data-feather="info" class="mr-50 align-middle"></i>
              <span><strong>Note:</strong> Harap mengisi format sesuai contoh yang ada di dalam kurung!</span>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- /Bootstrap Validation -->
</div>
</section>
<!-- /Validation -->

      </div>
    </div>
  </div>
@endsection

resources/views/characters/index.blade.php
@extends('layouts.admin.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Karakter Tables</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{{ route('welcome') }}">Home</a>
                  </li>
                  <li class="breadcrumb-item active">Table Karakter
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
          </div>
        </div>
      </div>


<!-- Table Hover Animation start -->
<div class="row" id="table-hover-animation">
<div class="col-12">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">List Karakter</h4>

      <a href="{{ route('karakter.create') }}" class="btn btn-success">+ Tambah</a>
    </div>
    <form class="d-flex" action="{{ route('karakter.index') }}" method="GET">
        <div class="col-2"><div><input type="text" class="form-control" name="search" value="{{ request()->query('search') }}" placeholder="Cari nomor induk"></div></div>
        <button class="btn btn-primary"><i data-feather="search"></i></button>
    </form>
    <div class="card-body">
    </div>
    <div class="table-responsive">
      <table class="table table-hover-animation">
        <thead>
          <tr>
            <th>NO. Induk</th>
            <th>Category Character</th>
            <th>Capaian</th>
            <th>Deskripsi</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            @forelse ($characters as $character)
            <tr>
                <td>{{ $character->student->nomor_induk }}</td>
                <td>{{ $character->karakter }}</td>
                <td>{{ $character->capaian }}</td>
                <td>{{ $character->deskripsi }}</td>
                <td>
                        <form action="{{ route('karakter.destroy',$character->id) }}" method="POST">
                                  <a class="btn btn-warning" href="{{ route('karakter.edit',$character->id) }}">
                                    <i data-feather="edit-2" class="mr-50"></i>
                                    <span>Edit</span>
                                  </a>

                                  @csrf
                                  @method('DELETE')
                                  <button class="btn btn-danger"><i data-feather="trash" class="mr-50"></i><span>Delete</span></button>
                        </form>
                </td>
              </tr>
            @empty
            <tr>
                <td colspan="6" class="text-center">
                    <p class="text-center">No result found for query <strong>{{ request()->query('search') }}</strong></p>
                </td>
            </tr>
            @endforelse
        </tbody>
      </table>
    </div>

  </div>
  {!! $characters->appends(['search' => request()->query('search')])->links() !!}
</div>
</div>
<!-- Table head options end -->

      </div>
    </div>
  </div>
@endsection