routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CharacterController;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\RombelController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\UserController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('auth')->name('welcome');
Route::get('/profile', [UserController::class, 'profile'])->name('profile');
Route::post('/avatar-post', [UserController::class, 'update_profile'])->name('profile.post');
Route::post('/change-password-post', [UserController::class, 'change_password'])->name('password.post');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('karakter', CharacterController::class);
Route::resource('siswa', StudentController::class);
Route::resource('rombel', RombelController::class);
Route::resource('jurusan', JurusanController::class);

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function character()
    {
        return $this->hasMany(Character::class, 'siswa_id');
    }

    public function rombel()
    {
        return $this->belongsTo(Rombel::class, 'rombel_id','id');
    }

    public function jurusan()
    {
        return $this->belongsTo(Jurusan::class, 'jurusan_id','id');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Jurusan;
use App\Models\Rombel;
use App\Models\Student;
use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;
use stdClass;

class StudentController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $students = Student::latest()->paginate(10);

        // return view('students.index', [
        //     'students' => $students
        // ]);
        Paginator::useBootstrap();
        $search = request()->query('search');

        if($search)
        {
            $students = Student::with('jurusan', 'rombel')->where('nomor_induk', 'LIKE', "%{$search}%")->paginate(10);
        }else {
            $students = Student::with('jurusan', 'rombel')->latest()->paginate(10);
        }

        return view('students.index', [
            'students' => $students,
        ])
        ->with('i');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jurusan = Jurusan::all();
        $rombel = Rombel::all();
        return view('students.create', compact('jurusan', 'rombel'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nomor_induk' => 'required|max:255',
            'nama' => 'required|max:50',
            'jurusan_id' => 'required|max:255',
            'tahun_pelajaran' => 'required|max:255',
            'rombel_id' => 'required|max:255',
            'semester' => 'required|max:20'
        ]);

        Student::create($request->all());

        return redirect()->route('siswa.index')
                        ->with('success','Data berhasil ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $jurusan = Jurusan::all();
        $rombel = Rombel::all();
        $student = Student::with('jurusan', 'rombel')->findOrFail($id);
        return view('students.edit', compact('student', 'rombel', 'jurusan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nomor_induk' => 'required|max:255',
            'nama' => 'required|max:50',
            'tahun_pelajaran' => 'required|max:255',
            'semester' => 'required|max:20'
        ]);

        $student = Student::findOrFail($id);
        $student->update($request->all());

        return redirect()->route('siswa.index')
                        ->with('success','Data berhasil diperbarui!');
    }

   /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $student = Student::findOrFail($id);

        $student->delete();

        return redirect()->route('siswa.index');
    }
}

resources/views/students/create.blade.php
@extends('layouts.admin.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Form Validation</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="index-2.html">Home</a>
                  </li>
                  <li class="breadcrumb-item"><a href="#">Forms</a>
                  </li>
                  <li class="breadcrumb-item active">Form Validation
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
            <div class="dropdown">
              <a class="btn-icon btn btn-danger btn-round btn-sm dropdown-toggle" href="{{ route('siswa.index') }}">Back</a>
            </div>
          </div>
        </div>
      </div>
      <div class="content-body"><!-- Validation -->
<section class="bs-validation">
<div class="row">
  <!-- Bootstrap Validation -->
  <div class="col-md-12 col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Bootstrap Validation</h4>
      </div>
      <div class="card-body">
        <form class="needs-validation" method="POST" action="{{ route('siswa.store') }}">
            @csrf
          <div class="form-group">
            <label class="form-label" for="basic-addon-name">Nomor Induk (NIS/NISN)</label>

            <input
              type="text"
              id="basic-addon-name"
              class="form-control"
              placeholder="Nomor Induk"
              name="nomor_induk"
              aria-describedby="basic-addon-name"
              required
            />
          </div>
          <div class="form-group">
            <label class="form-label" for="basic-default-email1">Nama Lengkap</label>
            <input
              type="text"
              id="basic-default-email1"
              class="form-control"
              name="nama"
              placeholder="Nama Lengkap"
              required
            />
          </div>
          <div class="form-group">
            <label class="form-label" for="basic-default-password1">Jurusan</label>
            <select class="form-control" name="jurusan_id" id="select-country1" required>
                <option value="" disabled selected>Pilih Jurusan</option>
                @foreach ($jurusan as $item)
                <option value="{{ $item->id }}">{{ $item->jurusan }}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
            <label for="select-country1">Tahun Pelajaran (2018 - 2021)</label>
            <input
              type="text"
              id="basic-default-password1"
              class="form-control"
              name="tahun_pelajaran"
              placeholder="Tahun Pelajaran"
              required
            />
          </div>
          <div class="form-group">
            <label for="dob-bootstrap-val">Rombel (RPL XII-2)</label>
            <select class="form-control" name="rombel_id" id="select-country1" required>
                <option value="" disabled selected>Pilih Rombel</option>
                @foreach ($rombel as $item)
                <option value="{{ $item->id }}">{{ $item->rombel }}</option>
                @endforeach
            </select>
          </div>
          <div class="form-group">
            <label for="customFile1">Semester</label>
            <div class="custom-file">
              <select class="form-control" name="semester" id="select-country1" required>
                <option value="" disabled selected>Pilih Semester</option>
                <option value="Semester 1">Semester 1</option>
                <option value="Semester 2">Semester 2</option>
                <option value="Semester 3">Semester 3</option>
                <option value="Semester 4">Semester 4</option>
                <option value="Semester 5">Semester 5</option>
                <option value="Semester 6">Semester 6</option>
              </select>
            </div>
          </div>
          <div class="alert alert-danger mt-1 alert-validation-msg" role="alert">
            <div class="alert-body">
              <i data-feather="info" class="mr-50 align-middle"></i>
              <span><strong>Note:</strong> Harap mengisi format sesuai contoh yang ada di dalam kurung!</span>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- /Bootstrap Validation -->
</div>
</section>
<!-- /Validation -->

      </div>
    </div>
  </div>
@endsection

resources/views/students/edit.blade.php
@extends('layouts.admin.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Form Validation</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="index-2.html">Home</a>
                  </li>
                  <li class="breadcrumb-item"><a href="#">Forms</a>
                  </li>
                  <li class="breadcrumb-item active">Form Validation
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
            <div class="dropdown">
              <a class="btn-icon btn btn-danger btn-round btn-sm dropdown-toggle" href="{{ route('siswa.index') }}">Back</a>
            </div>
          </div>
        </div>
      </div>
      <div class="content-body"><!-- Validation -->
<section class="bs-validation">
<div class="row">
  <!-- Bootstrap Validation -->
  <div class="col-md-12 col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Bootstrap Validation</h4>
      </div>
      <div class="card-body">
        <form class="needs-validation" method="POST" action="{{ route('siswa.update', $student->id) }}">
            @csrf
            @method('PUT')
          <div class="form-group">
            <label class="form-label" for="basic-addon-name">Nomor Induk (NIS/NISN)</label>

            <input
              type="text"
              id="basic-addon-name"
              class="form-control"
              value="{{ $student->nomor_induk }}"
              name="nomor_induk"
              aria-describedby="basic-addon-name"
              required
            />
          </div>
          <div class="form-group">
            <label class="form-label" for="basic-default-email1">Nama Lengkap</label>
            <input
              type="text"
              id="basic-default-email1"
              class="form-control"
              name="nama"
              value="{{ $student->nama }}"
              required
            />
          </div>
          <div class="form-group">
            <label class="form-label" for="basic-default-password1">Kompetensi</label>
            <select class="form-control" name="jurusan_id" id="select-country1" required>
                <option value="{{ $student->jurusan_id }}" disabled selected>{{ $student->jurusan->jurusan }}</option>
                                        @foreach ($jurusan as $item)
                                            <option value="{{ $item->id }}">{{ $item->jurusan }}</option>
                                        @endforeach
              </select>
          </div>
          <div class="form-group">
            <label for="select-country1">Tahun Pelajaran (2018 - 2021)</label>
            <input
              type="text"
              id="basic-default-password1"
              class="form-control"
              name="tahun_pelajaran"
              value="{{ $student->tahun_pelajaran }}"
              required
            />
          </div>
          <div class="form-group">
            <label for="dob-bootstrap-val">Rombel (RPL XII-2)</label>
            <select class="form-control" name="rombel_id" id="select-country1" required>
                <option value="{{ $student->rombel_id }}" disabled selected>{{ $student->rombel->rombel }}</option>
                                        @foreach ($rombel as $item)
                                            <option value="{{ $item->id }}">{{ $item->rombel }}</option>
                                        @endforeach
              </select>
          </div>
          <div class="form-group">
            <label for="customFile1">Semester</label>
            <div class="custom-file">
              <select class="form-control" name="semester" id="select-country1" required>
                <option value="{{ $student->semester }}" disabled selected>{{ $student->semester }}</option>
                <option value="Semester 1">Semester 1</option>
                <option value="Semester 2">Semester 2</option>
                <option value="Semester 3">Semester 3</option>
                <option value="Semester 4">Semester 4</option>
                <option value="Semester 5">Semester 5</option>
                <option value="Semester 6">Semester 6</option>
              </select>
            </div>
          </div>
          <div class="alert alert-danger mt-1 alert-validation-msg" role="alert">
            <div class="alert-body">
              <i data-feather="info" class="mr-50 align-middle"></i>
              <span><strong>Note:</strong> Harap mengisi format sesuai contoh yang ada di dalam kurung!</span>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- /Bootstrap Validation -->
</div>
</section>
<!-- /Validation -->

      </div>
    </div>
  </div>
@endsection

resources/views/students/index.blade.php
@extends('layouts.admin.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Siswa Tables</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{{ route('welcome') }}">Home</a>
                  </li>
                  <li class="breadcrumb-item active">Table Siswa
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
          </div>
        </div>
      </div>


<!-- Table Hover Animation start -->
<div class="row" id="table-hover-animation">
<div class="col-12">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">List Siswa</h4>

      <a href="{{ route('siswa.create') }}" class="btn btn-success">+ Tambah</a>
    </div>
    <form class="d-flex" action="{{ route('siswa.index') }}" method="GET">
        <div class="col-2"><div><input type="text" class="form-control" name="search" value="{{ request()->query('search') }}" placeholder="Cari nomor induk"></div></div>
        <button class="btn btn-primary"><i data-feather="search"></i></button>
    </form>
    <div class="card-body">
    </div>
    <div class="table-responsive">
      <table class="table table-hover-animation">
        <thead>
          <tr>
            <th>NO. Induk</th>
            <th>Nama</th>
            <th>Kompetensi</th>
            <th>Tahun Pelajaran</th>
            <th>Rombel</th>
            <th>Semester</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            @forelse ($students as $student)
            <tr>
                <td>{{ $student->nomor_induk }}</td>
                <td>{{ $student->nama }}</td>
                <td>{{ $student->jurusan->jurusan }}</td>
                <td>{{ $student->tahun_pelajaran }}</td>
                <td>{{ $student->rombel->rombel }}</td>
                <td>{{ $student->semester }}</td>
                <td>
                        <form action="{{ route('siswa.destroy',$student->id) }}" method="POST">
                                  <a class="btn btn-warning" href="{{ route('siswa.edit',$student->id) }}">
                                    <i data-feather="edit-2" class="mr-50"></i>
                                    <span>Edit</span>
                                  </a>

                                  @csrf
                                  @method('DELETE')
                                  <button class="btn btn-danger"><i data-feather="trash" class="mr-50"></i><span>Delete</span></button>
                        </form>
                </td>
              </tr>
            @empty
            <tr>
                <td colspan="7" class="text-center">
                    <p class="text-center">No result found for query <strong>{{ request()->query('search') }}</strong></p>
                </td>
            </tr>
            @endforelse
        </tbody>
      </table>
    </div>

  </div>
  {!! $students->appends(['search' => request()->query('search')])->links() !!}
</div>
</div>
<!-- Table head options end -->

      </div>
    </div>
  </div>
@endsection